#!/usr/bin/env bash

# If arg has numerical prefix
if (( 10#${1%%-*} >= 0 )) 2>/dev/null; then
  # Ensure leading zeroes
  prefix=$(printf %03d "$((10#${1%%-*}))")
else
  # Sub spaces with -
  prefix="${1// /-}"
fi
# An if-let would be nice! What steps do I need to redo this in bb?

# TODO HERE? Parse index files?

# Actual build process
npm install
npm run release

# TODO HERE? Update previous and next buttons?
# My thoughts. I think some combination of rewrite-clj or selmer templates would be much better than a bash script.

# Not really necessary just for isolation
dir="tmp/release/${prefix}"
mkdir -p "${dir}/"
mv resources/public/* "${dir}/"

# Pare to necessary files
rm "${dir}/favicon.ico" "${dir}/_js/compiled/manifest.edn"

echo "============================================================"
echo "Build output location:"
tree "${dir}"
echo "============================================================"
