name: Split the branch name.

on: workflow_dispatch

jobs:
  split-string:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@main

      - name: Split branch name
        env:
          BRANCH: ${{ github.ref_name }}
        id: split
        run: |
          echo "::set-output name=fragment::$(echo ${BRANCH##*-})"

      - name: Test variable
        run: |
          echo ${{ steps.split.outputs.fragment }}
